In [2]:
print('Hello')

Hello


In [0]:
import numpy as np

In [0]:
x = np.array([1,2,3])

In [5]:
a = np.zeros((2,2))
print(y)

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((2,2))
print(y+b)


[[-1. -1.]
 [-1. -1.]]


In [12]:
c = np.random.randint(10, size=(5))
d = np.random.randint(10, size=(5))
print(c)
print(d)

[1 5 4 9 4]
[5 8 3 1 1]


In [16]:
print(c==d)

[False False False False False]


In [15]:
np.dot(c,d)

70

In [29]:
ta = np.array([[22,5,16,9],[13,20,19,0],[5,9,1,16],[27,13,15,19]])
tb = np.array([[10,5,20,20],[5,21,22,27],[26,19,22,3],[27,8,18,7]])
tc = np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
td = np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])

print(np.add(ta,tb))
print(np.subtract(ta,tb))
print(ta*tb)
print(np.dot(ta,tb))
print(np.add(tc,td))
print(np.subtract(tc,td))
print(tc*td)
print(np.dot(tc,td))
print(ta+10)
print(tb+10)
print(tc+15)
print(td+15)
print((2*ta)+(2*tb))
print((ta+tb)*3)
print((ta-tb+ta-tb+tb)*4)

[[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]
[[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]
[[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]
[[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]
[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
2298
[[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
[[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]
[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]
[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]
[[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]
[[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]
[[ 136   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]
